FROM ghcr.io/muchobien/pocketbase:latest

RUN mkdir -p /pb/pb_data

COPY pb_init.sh /pb/pb_init.sh
COPY pb_entrypoint.sh /pb/pb_entrypoint.sh
RUN chmod +x /pb/pb_entrypoint.sh /pb/pb_init.sh

ENTRYPOINT ["/pb/pb_entrypoint.sh"]
